export const axonRegistryAbi = [
  {
    type: "function",
    name: "deployments",
    stateMutability: "view",
    inputs: [{ name: "factory", type: "address" }],
    outputs: [
      { name: "deploymentId", type: "bytes32" },
      { name: "deployer", type: "address" },
      { name: "factory", type: "address" },
      { name: "chainId", type: "uint256" },
      { name: "version", type: "string" },
      { name: "registeredAt", type: "uint64" },
      { name: "active", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "factoryOfVault",
    stateMutability: "view",
    inputs: [{ name: "vault", type: "address" }],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "factoriesByDeployer",
    stateMutability: "view",
    inputs: [{ name: "deployer", type: "address" }],
    outputs: [{ name: "", type: "address[]" }],
  },
  {
    type: "function",
    name: "platform",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "registerDeployment",
    stateMutability: "nonpayable",
    inputs: [
      { name: "factory", type: "address" },
      { name: "version", type: "string" },
    ],
    outputs: [{ name: "deploymentId", type: "bytes32" }],
  },
  {
    type: "function",
    name: "registerVault",
    stateMutability: "nonpayable",
    inputs: [
      { name: "factory", type: "address" },
      { name: "agentId", type: "bytes32" },
      { name: "vault", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "registerExistingVault",
    stateMutability: "nonpayable",
    inputs: [
      { name: "factory", type: "address" },
      { name: "vault", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "event",
    name: "DeploymentRegistered",
    anonymous: false,
    inputs: [
      { indexed: true, name: "deploymentId", type: "bytes32" },
      { indexed: true, name: "deployer", type: "address" },
      { indexed: true, name: "factory", type: "address" },
      { indexed: false, name: "chainId", type: "uint256" },
      { indexed: false, name: "version", type: "string" },
      { indexed: false, name: "registeredAt", type: "uint64" },
    ],
  },
  {
    type: "event",
    name: "PlatformInitialized",
    anonymous: false,
    inputs: [{ indexed: true, name: "platform", type: "address" }],
  },
  {
    type: "event",
    name: "VaultAttributed",
    anonymous: false,
    inputs: [
      { indexed: true, name: "deploymentId", type: "bytes32" },
      { indexed: true, name: "deployer", type: "address" },
      { indexed: true, name: "factory", type: "address" },
      { indexed: false, name: "vault", type: "address" },
      { indexed: false, name: "agentId", type: "bytes32" },
    ],
  },
] as const;
